# Generated by Django 5.1 on 2024-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestingModel',
            new_name='Model3',
        ),
    ]
